security:
    # Password hashers configuration
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Disable security for assets and profiler routes
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main firewall, enable form login
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login  # Path to the login form
                check_path: login  # Path where the form is submitted
                default_target_path: commande_create  # Default page after login

            logout:
                path: /logout  
                # Optionally, you can specify where the user will be redirected after logging out:
                target: /login

    # Access control rules
    access_control:
       
        # Only admins can access the /admin path
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Protect all other paths — require login
        - { path: ^/user, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
